### ISSUE TITLE
FuzzyCorrectionFilter should replace FuzzyCorrFilter, maybe?

### ISSUE THREAD

**Issue by mfschmidt** [UCL/PETPVC#101]
I'm working from Ubuntu 24.04 LTS, which uses gcc 13. I've also built InsightToolkit 5.4.0 locally with the same setup. I cloned the master branch of PETPVC and attempted to build it.

The compiler complained about "FuzzyCorrFilter" not existing when referenced in [petpvcFuzzyCorrectionFilter](https://github.com/UCL/PETPVC/blob/fb4e7279eb4c434aa68bb9f7554a5c20e071e6ba/lib/petpvcFuzzyCorrectionFilter.h#L56). It suggested I may have intended "FuzzyCorrectionFilter" instead.

```bash
In file included from /usr/local/include/ITK-6.0/itkLightObject.h:21,
                 from /usr/local/include/ITK-6.0/itkObject.h:31,
                 from /usr/local/include/ITK-6.0/itkRegion.h:31,
                 from /usr/local/include/ITK-6.0/itkImageRegion.h:31,
                 from /usr/local/include/ITK-6.0/itkImage.h:21,
                 from /home/mike/Projects/PETPVC/src/IterativeYang.cxx:34:
/home/mike/Projects/PETPVC/lib/petpvcFuzzyCorrectionFilter.h: In member function ‘const char* petpvc::FuzzyCorrectionFilter<TImage>::GetNameOfClass() const’:
/home/mike/Projects/PETPVC/lib/petpvcFuzzyCorrectionFilter.h:56:18: error: ‘FuzzyCorrFilter’ was not declared in this scope; did you mean ‘FuzzyCorrectionFilter’?
   56 |     itkTypeMacro(FuzzyCorrFilter, ImageToImageFilter);
      |                  ^~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/pvc_iy.dir/build.make:76: src/CMakeFiles/pvc_iy.dir/IterativeYang.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:300: src/CMakeFiles/pvc_iy.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

I'm a python coder who hasn't written C/C++ in many years, and I never got into type libraries, so I have no real idea what I'm doing here. But making that change allowed for my build to complete successfully.

**Comment by KrisThielemans** [comment]
You seem to be the first to try to compile with ITK 6.0. I have done some digging, and it appears that in previous versions of ITK, the first argument of `itkTypeMacro` could be anything at all (it was just used as a string), but [now](https://github.com/InsightSoftwareConsortium/ITK/blob/db46bb2f61ad6d8a87d641002b349bcec77ab817/Modules/Core/Common/include/itkMacro.h#L416-L422) it needs to be the class name.

I'll use your suggestion as a fix. Could you please confirm that `ctest` works fine, and indeed PETPVC works ok with ITK 6.0?

**Comment by mfschmidt** [comment]
Thanks, Kris!

Our only use of PETPVC is the following command.

```bash
petpvc \
-i /path/to/orig_01.nii.gz \
-o /path/to/pvc_01.nii.gz \
-m /path/to/mask_orig.nii.gz \
-p STC -x 5.9 -y 5.9 -z 5.9
```

I used it on 25 volumes with our prior environment (a ubuntu:jammy docker container with petpvc 1.2.11, compiled with ITK 5.2.1 and gcc12). I then used it on the same 25 volumes with my new local environment ( ubuntu:noble with petpvc 1.2.11, compiled with ITK 5.4.0 and gcc13). I compared the volumes from each build and the values at every voxel were identical in every image.

**Comment by mfschmidt** [comment]
From ctest:

```
Test project /opt/build_petpvc
      Start  1: generate
 1/23 Test  #1: generate ...................................   Passed    0.09 sec
      Start  2: simulate
 2/23 Test  #2: simulate ...................................   Passed    0.07 sec
      Start  3: RunIterativeYang
 3/23 Test  #3: RunIterativeYang ...........................   Passed    0.12 sec
      Start  4: CompareIterativeYang
 4/23 Test  #4: CompareIterativeYang .......................   Passed    0.07 sec
      Start  5: RunIterativeYangUndercorrect
 5/23 Test  #5: RunIterativeYangUndercorrect ...............   Passed    0.05 sec
      Start  6: CompareIterativeYangUndercorrect
 6/23 Test  #6: CompareIterativeYangUndercorrect ...........   Passed    0.01 sec
      Start  7: RunIterativeYangOvercorrect
 7/23 Test  #7: RunIterativeYangOvercorrect ................   Passed    0.06 sec
      Start  8: CompareIterativeYangOvercorrect
 8/23 Test  #8: CompareIterativeYangOvercorrect ............   Passed    0.01 sec
      Start  9: RunRBV
 9/23 Test  #9: RunRBV .....................................   Passed    0.09 sec
      Start 10: CompareRBV
10/23 Test #10: CompareRBV .................................   Passed    0.01 sec
      Start 11: RunRBVUndercorrect
11/23 Test #11: RunRBVUndercorrect .........................   Passed    0.03 sec
      Start 12: CompareRBVUndercorrect
12/23 Test #12: CompareRBVUndercorrect .....................   Passed    0.01 sec
      Start 13: RunRBVOvercorrect
13/23 Test #13: RunRBVOvercorrect ..........................   Passed    0.03 sec
      Start 14: CompareRBVOvercorrect
14/23 Test #14: CompareRBVOvercorrect ......................   Passed    0.01 sec
      Start 15: RunDiscreteIterativeYang
15/23 Test #15: RunDiscreteIterativeYang ...................   Passed    0.10 sec
      Start 16: CompareDiscreteIterativeYang
16/23 Test #16: CompareDiscreteIterativeYang ...............   Passed    0.01 sec
      Start 17: RunDiscreteIterativeYangUndercorrect
17/23 Test #17: RunDiscreteIterativeYangUndercorrect .......   Passed    0.03 sec
      Start 18: CompareDiscreteIterativeYangUndercorrect
18/23 Test #18: CompareDiscreteIterativeYangUndercorrect ...   Passed    0.01 sec
      Start 19: RunDiscreteIterativeYangOvercorrect
19/23 Test #19: RunDiscreteIterativeYangOvercorrect ........   Passed    0.04 sec
      Start 20: CompareDiscreteIterativeYangOvercorrect
20/23 Test #20: CompareDiscreteIterativeYangOvercorrect ....   Passed    0.01 sec
      Start 21: Compare_iy_diy
21/23 Test #21: Compare_iy_diy .............................   Passed    0.01 sec
      Start 22: Compare_iy_diy_Undercorrect
22/23 Test #22: Compare_iy_diy_Undercorrect ................   Passed    0.01 sec
      Start 23: Compare_iy_diy_Overcorrect
23/23 Test #23: Compare_iy_diy_Overcorrect .................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 23

Total Test time (real) =   0.94 sec
```

**Comment by KrisThielemans** [comment]
Excellent. Thanks @mfschmidt!

I'm marginally confused by you claiming to use ITK 5.4.0, while the error messages report ITK-6.0, but fine.

`master` has (a somewhat more elaborate version of) the fix. I will release PETPVC 1.12.2 soon, after sorting out some more CI issues.

**Comment by mfschmidt** [comment]
That's interesting. I intended to use 5.4.0 rather than 6.0, and I explicitly specified 5.4.0 to correct your 6.0 comment, but I now see your point and see the directory in my original error. Sorry for the confusion. I cloned their git repo and checked out the v5.4.0 branch, but I may have made a mistake or specified the wrong directory when I built it. I appreciate the correction/comment and I'll do some digging on my end. It's probably good either way here, so thanks for the rapid fix! :)
